/**
 * theme-config.js — SATU sumber kebenaran untuk kelima tema undangan.
 *
 * Dikonsumsi oleh:
 * - TraditionalLayout (classic-elegance, floral-blossom, floral-blue)
 * - designs/modern-minimalist & designs/nature-harmony (ambil accent/frame/particle)
 * - EnvelopeCover (cover)
 * - LivePhonePreview (preview)
 *
 * Catatan warna aksen: Tailwind tidak bisa mengompilasi class dinamis, jadi warna
 * hex di sini dipakai lewat `style` inline / CSS variable, bukan sebagai class.
 */

// ─── Chip specs untuk BankCard bersama ({ base, inner, cell }) ───
const CHIP_GOLD = {
  base: "bg-gradient-to-br from-yellow-100 via-yellow-300 to-amber-200",
  inner: "border-amber-400/60",
  cell: "bg-amber-300/60",
};
const CHIP_AMBER = {
  base: "bg-gradient-to-br from-yellow-300 via-amber-400 to-yellow-600 opacity-90",
  inner: "border-amber-600/60",
  cell: "bg-amber-500/60",
};
const CHIP_BLUE = {
  base: "bg-gradient-to-br from-cyan-200 via-sky-300 to-blue-200",
  inner: "border-blue-400/50",
  cell: "bg-blue-200/60",
};
const CHIP_ZINC = {
  base: "bg-gradient-to-br from-zinc-300 via-zinc-200 to-white",
  inner: "border-zinc-400/60",
  cell: "bg-zinc-300/60",
};

export const THEME_CONFIG = {
  "classic-elegance": {
    slug: "classic-elegance",
    name: "Classic Elegance",
    renderer: "traditional",
    accent: "#C8A96A",
    accentDark: "#b39150",
    accentDarker: "#9e7e40",
    fonts: { heading: "font-cormorant", name: "font-greatvibes" },
    frame: "gold-wreath",
    divider: "gold-star",
    particle: "gold",
    bankCard: {
      gradient: "linear-gradient(135deg, #C8A96A 0%, #8B6B30 40%, #5C4010 100%)",
      overlay: "stripes-circles",
      chipClass: CHIP_GOLD,
      providerFont: "cormorant",
    },
    hero: {
      pretitle: "✦ WALIMATUL 'URS ✦",
      pretitleReveal: "down",
      pretitleOpacity: 1,
      borderFrame: true,
      bgDecor: null,
      showDivider: true,
    },
    eventGradient: "linear-gradient(135deg, #C8A96A 0%, #7A5C1E 100%)",
    eventOverlay: "stripes",
    layout: {
      pageBg: "linear-gradient(180deg, #FEFCF8 0%, #FAF7F0 60%, #FEFCF8 100%)",
      surfaceBg: "linear-gradient(180deg, #FAF7F0 0%, #FEFCF8 100%)",
      text: "#1F1F1F",
      footerBg: "#C8A96A06",
    },
    copy: {
      coupleTitle: "Mempelai Pernikahan",
      coupleSubtitle: "Dengan rahmat Allah SWT, kami memperkenalkan diri",
      eventsTitle: "Jadwal Akad & Resepsi",
      eventsSubtitle: "Dengan segala kerendahan hati, kami mengundang Bapak/Ibu hadir",
      loveTitle: "Kisah Cinta Kami",
      galleryTitle: "Galeri Kebahagiaan",
      gallerySubtitle: "Setiap foto menyimpan kenangan yang tak terlupakan",
      giftsTitle: "Amplop Digital",
      giftsSubtitle: "Bagi yang berkenan memberikan tanda kasih untuk pengantin baru:",
      rsvpTitle: "Konfirmasi RSVP & Ucapan",
      rsvpSubtitle: "Berikan konfirmasi kehadiran dan doa restu terbaik:",
      guestbookLabel: "Buku Doa & Ucapan",
    },
    cover: {
      bg: "bg-[#F8F6F2]/90 dark:bg-zinc-950/90",
      textPrimary: "text-[#C8A96A]",
      textSecondary: "text-zinc-500 dark:text-zinc-400",
      fontName: "font-greatvibes text-3xl sm:text-4xl font-medium",
      cardBg: "bg-white/80 dark:bg-zinc-900/80 border-[#C8A96A]/20 shadow-xl",
      btnColor: "bg-[#C8A96A] text-white hover:bg-[#b39150] hover:shadow-[#C8A96A]/35",
      btnText: "text-[#C8A96A]",
      ornamentsColor: "#C8A96A",
      frameKind: "classic",
      particleType: "gold",
      layout: "fullbleed",
      guestCardShape: "rounded-2xl",
    },
    preview: {
      previewBg: "bg-[#F8F6F2] dark:bg-[#191919]",
      accentBg: "bg-[#C8A96A]/15 border-[#C8A96A]/30 text-[#C8A96A]",
      primaryBtn: "bg-[#C8A96A] text-white",
    },
  },

  "floral-blossom": {
    slug: "floral-blossom",
    name: "Floral Blossom",
    renderer: "traditional",
    accent: "#B76E79",
    accentDark: "#a65f6a",
    accentDarker: "#8B3E4A",
    fonts: { heading: "font-playfair", name: "font-greatvibes" },
    frame: "floral",
    divider: "heart",
    particle: "petals",
    bankCard: {
      // Semua kartu bank memakai gradient rose agar selaras dengan palet tema
      // (sebelumnya bank non-BCA/BNI tampil navy — keluar dari palet rose).
      gradient: "linear-gradient(135deg, #B76E79 0%, #8B3E4A 50%, #5C1F2B 100%)",
      overlay: "glass",
      chipClass: CHIP_AMBER,
      providerFont: null,
    },
    hero: {
      pretitle: "✦ THE WEDDING CELEBRATION ✦",
      pretitleReveal: "down",
      pretitleOpacity: 1,
      borderFrame: false,
      bgDecor: "rose",
      showDivider: false,
    },
    eventGradient: "linear-gradient(135deg, #B76E79 0%, #8B3E4A 100%)",
    eventOverlay: "circle",
    layout: {
      pageBg: "linear-gradient(180deg, #FFF3F5 0%, #FFF8F9 60%, #FFF3F5 100%)",
      surfaceBg: "linear-gradient(180deg, #FFF8F9 0%, #FFF3F5 100%)",
      text: "#3A2A2D",
      footerBg: "#B76E7908",
    },
    copy: {
      coupleTitle: "Mempelai Pengantin",
      coupleSubtitle: "Dengan penuh rasa syukur, kami memperkenalkan diri",
      eventsTitle: "Jadwal Akad & Resepsi",
      eventsSubtitle: "Dengan segala kerendahan hati, kami mengundang Bapak/Ibu untuk hadir",
      loveTitle: "Perjalanan Cinta",
      galleryTitle: "Galeri Momen",
      gallerySubtitle: "Setiap foto menyimpan seribu cerita cinta",
      giftsTitle: "Amplop Digital",
      giftsSubtitle: "Bagi Anda yang berkenan memberikan tanda kasih untuk pengantin baru:",
      rsvpTitle: "RSVP & Buku Ucapan",
      rsvpSubtitle: "Berikan konfirmasi kehadiran Anda beserta doa terbaik:",
      guestbookLabel: "Doa & Restu Tamu",
    },
    cover: {
      bg: "bg-[#F8F6F2]/90 dark:bg-zinc-950/90",
      solid: "bg-[#F8F6F2] dark:bg-zinc-950",
      textPrimary: "text-[#B76E79]",
      textSecondary: "text-zinc-500 dark:text-zinc-400",
      fontName: "font-greatvibes text-3xl sm:text-4xl font-medium",
      cardBg: "bg-white/85 dark:bg-zinc-900/80 border-[#B76E79]/20 shadow-xl",
      btnColor: "bg-[#B76E79] text-white hover:bg-[#a65f6a] hover:shadow-[#B76E79]/35",
      btnText: "text-[#B76E79]",
      ornamentsColor: "#B76E79",
      frameKind: "floral-blossom",
      cardName: "text-zinc-800",
      cardMuted: "text-zinc-500",
      particleType: "petals",
      layout: "framed",
      guestCardShape: "rounded-2xl",
    },
    preview: {
      previewBg: "bg-rose-50/70 dark:bg-[#1f1618]",
      accentBg: "bg-rose-100 border-rose-300 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300",
      primaryBtn: "bg-rose-600 text-white",
    },
  },

  "floral-blue": {
    slug: "floral-blue",
    name: "Floral Blue",
    renderer: "traditional",
    accent: "#1A365D",
    accentDark: "#122744",
    accentDarker: "#0d1a30",
    fonts: { heading: "font-baskerville", name: "font-greatvibes" },
    frame: "blue-leaf",
    divider: "wave",
    particle: "bubbles",
    bankCard: {
      gradient: "linear-gradient(135deg, #1A365D 0%, #2D5282 50%, #1A365D 100%)",
      overlay: "wave",
      chipClass: CHIP_BLUE,
      providerFont: "cormorant",
    },
    hero: {
      pretitle: "✦ THE WEDDING CELEBRATION OF ✦",
      pretitleReveal: "fade",
      pretitleOpacity: 0.7,
      borderFrame: false,
      bgDecor: "wave",
      showDivider: true,
    },
    eventGradient: "linear-gradient(135deg, #1A365D 0%, #2D5282 100%)",
    eventOverlay: "wave",
    layout: {
      pageBg: "linear-gradient(180deg, #EBF8FF 0%, #F0F4F8 60%, #EBF8FF 100%)",
      surfaceBg: "#E8F4FD80",
      text: "#0F1E36",
      footerBg: "#1A365D06",
    },
    copy: {
      coupleTitle: "Mempelai Pengantin",
      coupleSubtitle: "Dengan penuh rasa syukur kami memperkenalkan diri",
      eventsTitle: "Jadwal Akad & Resepsi",
      eventsSubtitle: "Dengan segala kerendahan hati, kami mengundang Bapak/Ibu untuk hadir",
      loveTitle: "Perjalanan Cinta",
      galleryTitle: "Galeri Momen",
      gallerySubtitle: "Abadikan setiap momen bersama",
      giftsTitle: "Amplop Digital",
      giftsSubtitle: "Bagi yang berkenan memberikan tanda kasih:",
      rsvpTitle: "RSVP & Buku Ucapan",
      rsvpSubtitle: "Konfirmasi kehadiran dan doa terbaik:",
      guestbookLabel: "Doa & Restu",
    },
    cover: {
      bg: "bg-[#E8F4FD]/90 dark:bg-[#0b1420]/90",
      solid: "bg-[#E8F4FD] dark:bg-[#0b1420]",
      textPrimary: "text-[#1A365D]",
      textSecondary: "text-zinc-500 dark:text-zinc-400",
      fontName: "font-greatvibes text-3xl sm:text-4xl font-medium",
      cardBg: "bg-white/80 dark:bg-zinc-900/80 border-[#1A365D]/20 shadow-xl",
      btnColor: "bg-[#1A365D] text-white hover:bg-[#122744] hover:shadow-[#1A365D]/35",
      btnText: "text-[#1A365D]",
      ornamentsColor: "#1A365D",
      frameKind: "floral-blue",
      cardName: "text-zinc-800",
      cardMuted: "text-zinc-500",
      particleType: "bubbles",
      layout: "framed",
      guestCardShape: "rounded-2xl",
    },
    preview: {
      previewBg: "bg-sky-50/70 dark:bg-[#121d28]",
      accentBg: "bg-sky-100 border-sky-300 text-sky-700 dark:bg-sky-950/40 dark:text-sky-300",
      primaryBtn: "bg-sky-600 text-white",
    },
  },

  "modern-minimalist": {
    slug: "modern-minimalist",
    name: "Modern Minimalist",
    renderer: "modern",
    accent: "#0F172A",
    accentDark: "#1E293B",
    accentDarker: "#020617",
    fonts: { heading: "font-sans", name: "font-sans" },
    frame: "geometric",
    divider: "line",
    particle: null,
    bankCard: {
      gradient: "linear-gradient(135deg, #0F172A 0%, #1E293B 50%, #0F172A 100%)",
      overlay: "grid-glow",
      chipClass: CHIP_ZINC,
      providerFont: null,
    },
    hero: {
      pretitle: "✦ JOIN US TO CELEBRATE ✦",
      pretitleReveal: "fade",
      pretitleOpacity: 1,
      borderFrame: true,
      bgDecor: null,
      showDivider: true,
    },
    eventGradient: "#0F172A",
    eventOverlay: null,
    layout: {
      pageBg: "linear-gradient(180deg, #FAFAF9 0%, #F4F4F2 60%, #FAFAF9 100%)",
      surfaceBg: "#F4F4F2",
      text: "#1E293B",
      footerBg: "transparent",
    },
    copy: {},
    cover: {
      bg: "bg-[#0F172A]/90 dark:bg-[#090d16]/95",
      solid: "bg-[#0F172A] dark:bg-[#090d16]",
      textPrimary: "text-zinc-100",
      textSecondary: "text-zinc-400",
      fontName: "font-sans font-black text-xl sm:text-2xl tracking-widest uppercase",
      cardBg: "bg-slate-900/90 dark:bg-zinc-900/90 border-slate-700/60 shadow-2xl",
      btnColor: "bg-zinc-100 text-slate-950 hover:bg-white hover:shadow-white/20",
      btnText: "text-zinc-200",
      ornamentsColor: "#FFFFFF",
      frameKind: "modern",
      cardName: "text-zinc-100",
      cardMuted: "text-zinc-400",
      particleType: "grid",
      layout: "framed",
      guestCardShape: "rounded-none",
    },
    preview: {
      previewBg: "bg-slate-50 dark:bg-[#111827]",
      accentBg: "bg-slate-200 border-slate-300 text-slate-800 dark:bg-slate-800 dark:text-slate-200",
      primaryBtn: "bg-slate-800 text-white",
    },
  },

  "nature-harmony": {
    slug: "nature-harmony",
    name: "Nature Harmony",
    renderer: "nature",
    accent: "#4A6B3D",
    accentDark: "#2F4A28",
    accentDarker: "#1B2E16",
    fonts: { heading: "font-fraunces", name: "font-greatvibes" },
    frame: "blob",
    divider: "leaf",
    particle: "leaves",
    bankCard: {
      gradient: "linear-gradient(135deg, #4A6B3D 0%, #2F4A28 50%, #1B2E16 100%)",
      overlay: "glass",
      chipClass: CHIP_AMBER,
      providerFont: null,
    },
    hero: {
      pretitle: "✦ THE WEDDING CELEBRATION ✦",
      pretitleReveal: "down",
      pretitleOpacity: 1,
      borderFrame: false,
      bgDecor: null,
      showDivider: false,
    },
    eventGradient: "linear-gradient(135deg, #4A6B3D 0%, #2F4A28 100%)",
    eventOverlay: "circle",
    layout: {
      pageBg: "linear-gradient(180deg, #F7F5EE 0%, #FBFAF6 60%, #F7F5EE 100%)",
      surfaceBg: "linear-gradient(180deg, #FBFAF6 0%, #F7F5EE 100%)",
      text: "#2E3B27",
      footerBg: "#4A6B3D08",
    },
    copy: {},
    cover: {
      bg: "bg-[#F7F5EE]/90 dark:bg-[#171d14]/95",
      solid: "bg-[#F7F5EE] dark:bg-[#171d14]",
      textPrimary: "text-[#4A6B3D]",
      textSecondary: "text-zinc-500 dark:text-zinc-400",
      fontName: "font-greatvibes text-3xl sm:text-4xl font-medium",
      cardBg: "bg-white/85 dark:bg-zinc-900/80 border-[#4A6B3D]/20 shadow-xl",
      btnColor: "bg-[#4A6B3D] text-white hover:bg-[#3c5732] hover:shadow-[#4A6B3D]/35",
      btnText: "text-[#4A6B3D]",
      ornamentsColor: "#4A6B3D",
      frameKind: "blob",
      cardName: "text-zinc-800",
      cardMuted: "text-zinc-500",
      particleType: "leaves",
      layout: "framed",
      guestCardShape: "rounded-2xl",
    },
    preview: {
      previewBg: "bg-[#F7F5EE] dark:bg-[#171d14]",
      accentBg: "bg-green-100 border-green-300 text-green-700 dark:bg-green-950/40 dark:text-green-300",
      primaryBtn: "bg-[#4A6B3D] text-white",
    },
  },
};

/**
 * Ambil konfigurasi tema berdasarkan slug; fallback ke classic-elegance.
 */
export function getThemeConfig(slug) {
  return THEME_CONFIG[slug] || THEME_CONFIG["classic-elegance"];
}
